const JIKAN='https://api.jikan.moe/v4';
const ANILIST='https://graphql.anilist.co';
const KITSU='https://kitsu.io/api/edge';
const FIREBASE_VERSION='12.18.0';
const FIREBASE_CONFIG={apiKey:'AIzaSyBF3jubXpba2G8CPszVN-Dip-3OWs_EUoE',authDomain:'hubs-b9c39.firebaseapp.com',projectId:'hubs-b9c39',storageBucket:'hubs-b9c39.firebasestorage.app',messagingSenderId:'699995857695',appId:'1:699995857695:web:240f8598fb4100d7cf462a'};
const LOCAL_KEY='mgAnimeSubscriptions',PREF_KEY='mgAnimePreference';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const cache=new Map();
let jikanQueue=Promise.resolve(),nextJikanAt=0,aniQueue=Promise.resolve(),nextAniAt=0;
const JIKAN_GAP=800,ANILIST_GAP=2200;
function queueRequest(kind,url,options={},gap){const job=(kind==='jikan'?jikanQueue:aniQueue).then(async()=>{const next=kind==='jikan'?nextJikanAt:nextAniAt;const wait=Math.max(0,next-Date.now());if(wait)await sleep(wait);if(kind==='jikan')nextJikanAt=Date.now()+gap;else nextAniAt=Date.now()+gap;return request(url,options)});if(kind==='jikan')jikanQueue=job.catch(()=>{});else aniQueue=job.catch(()=>{});return job}
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function getAnimeId(a){return a?.id||((a?.malId!=null)?`anime:mal:${a.malId}`:`anime:unknown:${String(a?.title||'').toLowerCase()}`)}
function normalizeJikan(a={}){const b=a.broadcast||{};return{id:`anime:mal:${a.mal_id}`,malId:a.mal_id,title:a.title||a.title_japanese||'Unknown title',englishTitle:a.title_english||null,japaneseTitle:a.title_japanese||null,image:a.images?.jpg?.large_image_url||a.images?.jpg?.image_url||'',score:a.score??null,year:a.year??a.aired?.prop?.from?.year??'—',type:a.type||'Anime',status:a.status||'Unknown',synopsis:a.synopsis||'',genres:(a.genres||[]).map(x=>x?.name).filter(Boolean),episodes:a.episodes??null,duration:a.duration??null,rating:a.rating??null,nextEpisodeAt:null,nextEpisode:null,broadcastDay:b.day||null,broadcastTime:b.time||null,broadcastTimezone:b.timezone||null,provider:'jikan'}}
function normalizeAniList(a={}){const t=a.title||{};return{id:a.idMal?`anime:mal:${a.idMal}`:`anime:anilist:${a.id}`,malId:a.idMal||null,anilistId:a.id,title:t.english||t.romaji||t.native||'Unknown title',englishTitle:t.english||null,japaneseTitle:t.native||null,image:a.coverImage?.extraLarge||a.coverImage?.large||'',score:a.averageScore?Number(a.averageScore)/10:null,year:a.startDate?.year??'—',type:a.format||'Anime',status:a.status==='RELEASING'?'Currently Airing':a.status||'Unknown',synopsis:a.description||'',genres:a.genres||[],episodes:a.episodes??null,duration:a.duration??null,rating:null,nextEpisodeAt:a.nextAiringEpisode?.airingAt?a.nextAiringEpisode.airingAt*1000:null,nextEpisode:a.nextAiringEpisode?.episode??null,provider:'anilist'}}
function normalizeKitsu(a={}){const x=a.attributes||{},t=x.titles||{};return{id:`anime:kitsu:${a.id}`,malId:null,kitsuId:a.id,title:t.en||x.canonicalTitle||t.en_jp||t.ja_jp||'Unknown title',englishTitle:t.en||x.canonicalTitle||null,japaneseTitle:t.ja_jp||null,image:x.posterImage?.large||x.posterImage?.medium||x.posterImage?.original||'',score:x.averageRating?Number(x.averageRating)/10:null,year:x.startDate?Number(String(x.startDate).slice(0,4)):'—',type:x.subtype||'Anime',status:x.status||'Unknown',synopsis:x.synopsis||x.description||'',genres:[],episodes:x.episodeCount??null,duration:x.episodeLength?`${x.episodeLength} min`:null,rating:x.ageRating||null,nextEpisodeAt:x.nextRelease?new Date(x.nextRelease).getTime():null,nextEpisode:null,provider:'kitsu'}}
function cacheGet(key,maxAge){const v=cache.get(key);return v&&Date.now()-v.time<maxAge?v.data:null}
function cacheSet(key,data){cache.set(key,{time:Date.now(),data});return data}
async function request(url,options={}){let last;for(let i=0;i<3;i++){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);const r=await fetch(url,{...options,signal:c.signal,headers:{Accept:'application/json',...(options.headers||{})}});clearTimeout(t);if(r.ok)return await r.json();const retry=Number(r.headers.get('Retry-After'));if(r.status===429&&Number.isFinite(retry))await sleep(Math.min(Math.max(retry*1000,1500),15000));if(r.status!==429&&r.status<500)throw new Error(`HTTP ${r.status}`);last=new Error(`HTTP ${r.status}`)}catch(e){last=e}if(i<2)await sleep(1200*(i+1))}throw last||new Error('Request failed')}
async function aniListRequest(query,variables={}){const key=`al:${query}:${JSON.stringify(variables)}`,hit=cacheGet(key,120000);if(hit)return hit;const json=await queueRequest('anilist',ANILIST,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables})},ANILIST_GAP);if(json?.errors?.length)throw new Error(json.errors[0].message||'AniList error');return cacheSet(key,json)}
async function fetchJikan(path){const key=`j:${path}`,hit=cacheGet(key,300000);if(hit)return hit;if(path.startsWith('/top/anime')){try{return cacheSet(key,await anilistList({sort:path.includes('order_by=score')?'SCORE_DESC':'POPULARITY_DESC',perPage:12}))}catch{}}if(path.startsWith('/anime?status=airing')){try{return cacheSet(key,await anilistList({sort:'POPULARITY_DESC',status:'RELEASING',perPage:12}))}catch{}}const json=await queueRequest('jikan',`${JIKAN}${path}`,{},JIKAN_GAP);const data=Array.isArray(json.data)?json.data.map(normalizeJikan):[];return cacheSet(key,data)}
async function fetchKitsu(path){const key=`k:${path}`,hit=cacheGet(key,300000);if(hit)return hit;const json=await request(`${KITSU}${path}`,{headers:{Accept:'application/vnd.api+json'}});const data=Array.isArray(json.data)?json.data.map(normalizeKitsu):[];return cacheSet(key,data)}
const LIST_QUERY=`query($page:Int,$perPage:Int,$sort:[MediaSort],$status:MediaStatus,$search:String){Page(page:$page,perPage:$perPage){media(type:ANIME,isAdult:false,status:$status,search:$search,sort:$sort){id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status description genres episodes duration startDate{year} nextAiringEpisode{airingAt episode}}}}`;
async function anilistList({sort='POPULARITY_DESC',status=null,search=null,perPage=12}={}){const json=await aniListRequest(LIST_QUERY,{page:1,perPage,sort:[sort],status,search});return(json.data?.Page?.media||[]).map(normalizeAniList)}
async function searchAnime(q){const query=String(q||'').trim();if(!query)return[];const key=`search:${query.toLowerCase()}`,hit=cacheGet(key,600000);if(hit)return hit;try{const data=await anilistList({sort:'SEARCH_MATCH_DESC',search:query,perPage:12});if(data.length)return cacheSet(key,data)}catch{}try{const data=await fetchJikan(`/anime?q=${encodeURIComponent(query)}&limit=12&sfw=true`);if(data.length)return cacheSet(key,data)}catch{}try{return cacheSet(key,await fetchKitsu(`/anime?filter[text]=${encodeURIComponent(query)}&page[limit]=12`))}catch{}throw new Error('All anime search providers failed')}
function jikanNextBroadcast(a){if(!a.broadcastDay||!a.broadcastTime)return null;const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],target=days.indexOf(a.broadcastDay);if(target<0)return null;const parts=String(a.broadcastTime).split(':').map(Number);if(parts.length<2)return null;const now=new Date(),candidate=new Date(now),delta=(target-now.getDay()+7)%7;candidate.setDate(now.getDate()+delta);candidate.setHours(parts[0],parts[1],0,0);if(candidate<=now)candidate.setDate(candidate.getDate()+7);return candidate.getTime()}
async function fetchCountdown(){const hit=cacheGet('countdown',90000);if(hit)return hit;try{const data=(await anilistList({sort:'START_DATE_DESC',status:'RELEASING',perPage:50})).filter(a=>a.nextEpisodeAt&&a.nextEpisodeAt>Date.now()).sort((a,b)=>a.nextEpisodeAt-b.nextEpisodeAt).slice(0,24);return cacheSet('countdown',data)}catch{}const fallback=(await fetchJikan('/anime?status=airing&order_by=popularity&sort=desc&limit=24')).map(a=>({...a,nextEpisodeAt:jikanNextBroadcast(a)})).filter(a=>a.nextEpisodeAt&&a.nextEpisodeAt>Date.now()).sort((a,b)=>a.nextEpisodeAt-b.nextEpisodeAt);return cacheSet('countdown',fallback)}
const DETAIL_QUERY=`query($id:Int){Media(idMal:$id,type:ANIME){id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status description genres episodes duration startDate{year} endDate{year} season seasonYear countryOfOrigin source synonyms trailer{site id} nextAiringEpisode{airingAt episode} relations{edges{relationType node{type id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status episodes startDate{year}}}} recommendations(perPage:12,sort:RATING_DESC){nodes{mediaRecommendation{id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status startDate{year}}}}}}`;
async function fetchAnimeDetails(id){const n=Number(id);if(!Number.isInteger(n)||n<1)throw new Error('Invalid anime id');const key=`detail:${n}`,hit=cacheGet(key,600000);if(hit)return hit;try{const json=await aniListRequest(DETAIL_QUERY,{id:n});const raw=json.data?.Media;if(raw){const a=normalizeAniList(raw);a.trailer=raw.trailer?.site==='youtube'&&raw.trailer?.id?`https://www.youtube.com/watch?v=${raw.trailer.id}`:null;a.source=raw.source||null;a.countryOfOrigin=raw.countryOfOrigin||null;a.season=raw.season||null;a.seasonYear=raw.seasonYear||null;a.startDate=raw.startDate||null;a.endDate=raw.endDate||null;a.synonyms=raw.synonyms||[];a.nextSeasonYear=null;const relations=(raw.relations?.edges||[]).filter(e=>e?.node?.type==='ANIME'&&e?.node?.id);a.related=relations.map(e=>({...normalizeAniList(e.node),relationType:e.relationType}));a.seasons=relations.filter(e=>['PREQUEL','SEQUEL','SIDE_STORY','ALTERNATIVE'].includes(e.relationType)).map(e=>({...normalizeAniList(e.node),relationType:e.relationType}));const sequel=relations.find(e=>e.relationType==='SEQUEL');if(sequel?.node?.startDate?.year)a.nextSeasonYear=sequel.node.startDate.year;a.recommendations=(raw.recommendations?.nodes||[]).map(x=>normalizeAniList(x.mediaRecommendation||{})).filter(x=>x.id);return cacheSet(key,a)}}catch{}const json=await fetchJikan(`/anime/${n}/full`);if(!json?.data)throw new Error('Anime not found');const a=normalizeJikan(json.data);a.trailer=json.data.trailer?.url||json.data.trailer?.embed_url||null;a.source=null;a.countryOfOrigin=null;a.season=null;a.seasonYear=null;a.nextSeasonYear=null;a.startDate=json.data.aired?.from||null;a.endDate=json.data.aired?.to||null;a.related=[];a.seasons=[];a.recommendations=[];return cacheSet(key,a)}
async function fetchAnimeRecommendations(id){const n=Number(id);if(!Number.isInteger(n)||n<1)throw new Error('Invalid anime id');const key=`rec:${n}`,hit=cacheGet(key,600000);if(hit)return hit;try{const json=await aniListRequest(`query($id:Int){Media(idMal:$id,type:ANIME){recommendations(perPage:12,sort:RATING_DESC){nodes{mediaRecommendation{id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status startDate{year} genres}}}}}}`,{id:n});const data=(json.data?.Media?.recommendations?.nodes||[]).map(x=>normalizeAniList(x.mediaRecommendation||{})).filter(x=>x.id);if(data.length)return cacheSet(key,data)}catch{}const json=await fetchJikan(`/anime/${n}/recommendations`);const data=(Array.isArray(json.data)?json.data:[]).slice(0,12).map(x=>normalizeJikan(x.entry||{})).filter(x=>x.malId);return cacheSet(key,data)}
function animeCard(a,extra=''){const title=a.englishTitle||a.title||'Unknown title';const img=a.image?`<img src="${escapeHtml(a.image)}" alt="${escapeHtml(title)}" loading="lazy" onerror="this.onerror=null;this.removeAttribute('src');this.alt='Anime poster unavailable';">`:'<div class="anime-card-image">🎌</div>';const detail=a.malId?`<a class="btn secondary" href="anime-detail.html?id=${encodeURIComponent(a.malId)}">Details</a>`:'';return`<article class="anime-card">${img}<div class="anime-card-copy"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(a.year||'—')} · ⭐ ${escapeHtml(a.score??'—')}</p><p>${escapeHtml(a.type||'Anime')} · ${escapeHtml(a.status||'Unknown')}</p><div class="card-actions">${detail}${extra}</div></div></article>`}
let firebasePromise;async function initFirebase(){if(firebasePromise)return firebasePromise;firebasePromise=(async()=>{const appM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`);const authM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`);const fsM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`);const app=appM.getApps().length?appM.getApps()[0]:appM.initializeApp(FIREBASE_CONFIG);const auth=authM.getAuth(app),db=fsM.getFirestore(app);return{...authM,...fsM,auth,db}})();return firebasePromise}
async function getCurrentUser(){try{const f=await initFirebase();return f.auth.currentUser||await new Promise(resolve=>{let done=false;const stop=f.onAuthStateChanged(f.auth,u=>{if(done)return;done=true;stop();resolve(u||null)});setTimeout(()=>{if(!done){done=true;try{stop()}catch{}resolve(f.auth.currentUser||null)}},2500)})}catch{return null}}
function localSubs(){try{const x=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveLocal(x){localStorage.setItem(LOCAL_KEY,JSON.stringify(x))}
async function saveSubscription(item){const f=await initFirebase(),u=f.auth.currentUser;if(u){const id=String(item.id).replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,120);await f.setDoc(f.doc(f.db,'users',u.uid,'subscriptions',id),{...item,id,updated:new Date().toISOString()},{merge:true});return true}const list=localSubs(),i=list.findIndex(x=>String(x.id)===String(item.id));if(i>=0)list[i]=item;else list.push(item);saveLocal(list);return false}
async function deleteSubscription(id){const f=await initFirebase(),u=f.auth.currentUser;if(u){await f.deleteDoc(f.doc(f.db,'users',u.uid,'subscriptions',String(id).replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,120)));return}saveLocal(localSubs().filter(x=>String(x.id)!==String(id)))}
async function loadSubscriptions(){const f=await initFirebase(),u=f.auth.currentUser;if(!u)return localSubs();const snap=await f.getDocs(f.collection(f.db,'users',u.uid,'subscriptions'));return snap.docs.map(d=>d.data())}
async function getPreferredLanguage(){const local=localStorage.getItem(PREF_KEY)||'Hindi';try{const f=await initFirebase(),u=f.auth.currentUser;if(!u)return local;const d=await f.getDoc(f.doc(f.db,'users',u.uid,'profile','preferences'));return d.exists()&&d.data()?.animeLanguage?d.data().animeLanguage:local}catch{return local}}
async function savePreferredLanguage(language){const value=String(language||'Hindi');localStorage.setItem(PREF_KEY,value);try{const f=await initFirebase(),u=f.auth.currentUser;if(!u)return false;await f.setDoc(f.doc(f.db,'users',u.uid,'profile','preferences'),{animeLanguage:value,updated:new Date().toISOString()},{merge:true});return true}catch{return false}}
export{searchAnime,fetchJikan,fetchCountdown,fetchAnimeDetails,fetchAnimeRecommendations,animeCard,getAnimeId,escapeHtml,getCurrentUser,saveSubscription,deleteSubscription,loadSubscriptions,anilistList,getPreferredLanguage,savePreferredLanguage};