const JIKAN='https://api.jikan.moe/v4';
const ANILIST='https://graphql.anilist.co';
const FIREBASE_VERSION='12.18.0';
const FIREBASE_CONFIG={apiKey:'AIzaSyBF3jubXpba2G8CPszVN-Dip3-OWs_EUoE',authDomain:'hubs-b9c39.firebaseapp.com',projectId:'hubs-b9c39',storageBucket:'hubs-b9c39.firebasestorage.app',messagingSenderId:'699995857695',appId:'1:699995857695:web:240f8598fb4100d7cf462a'};
const LOCAL_KEY='mgAnimeSubscriptions';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const cache=new Map();
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function getAnimeId(a){return a?.id||((a?.malId!=null)?`anime:mal:${a.malId}`:`anime:unknown:${String(a?.title||'').toLowerCase()}`)}
function normalizeJikan(a={}){return{id:`anime:mal:${a.mal_id}`,malId:a.mal_id,title:a.title||a.title_japanese||'Unknown title',englishTitle:a.title_english||null,japaneseTitle:a.title_japanese||null,image:a.images?.jpg?.large_image_url||a.images?.jpg?.image_url||'',score:a.score??null,year:a.year??a.aired?.prop?.from?.year??'—',type:a.type||'Anime',status:a.status||'Unknown',synopsis:a.synopsis||'',genres:(a.genres||[]).map(x=>x?.name).filter(Boolean),episodes:a.episodes??null,duration:a.duration??null,rating:a.rating??null,nextEpisodeAt:null,nextEpisode:null,provider:'jikan'}}
function normalizeAniList(a={}){const t=a.title||{};return{id:a.idMal?`anime:mal:${a.idMal}`:`anime:anilist:${a.id}`,malId:a.idMal||null,anilistId:a.id,title:t.english||t.romaji||t.native||'Unknown title',englishTitle:t.english||null,japaneseTitle:t.native||null,image:a.coverImage?.extraLarge||a.coverImage?.large||'',score:a.averageScore?Number(a.averageScore)/10:null,year:a.startDate?.year??'—',type:a.format||'Anime',status:a.status==='RELEASING'?'Currently Airing':a.status||'Unknown',synopsis:a.description||'',genres:a.genres||[],episodes:a.episodes??null,duration:a.duration??null,rating:null,nextEpisodeAt:a.nextAiringEpisode?.airingAt?a.nextAiringEpisode.airingAt*1000:null,nextEpisode:a.nextAiringEpisode?.episode??null,provider:'anilist'}}
async function request(url,options={}){let last;for(let i=0;i<3;i++){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);const r=await fetch(url,{...options,signal:c.signal,headers:{Accept:'application/json',...(options.headers||{})}});clearTimeout(t);if(r.ok)return await r.json();if(r.status!==429&&r.status<500)throw new Error(`HTTP ${r.status}`);last=new Error(`HTTP ${r.status}`)}catch(e){last=e}if(i<2)await sleep(700*(i+1))}throw last||new Error('Request failed')}
async function fetchJikan(path){const key=path;if(cache.has(key)&&Date.now()-cache.get(key).time<90000)return cache.get(key).data;try{const json=await request(`${JIKAN}${path}`);const data=Array.isArray(json.data)?json.data.map(normalizeJikan):[];cache.set(key,{time:Date.now(),data});return data}catch(e){const p=new URLSearchParams(path.split('?')[1]||'');const q=p.get('q');if(!q)throw e;const query=`query($search:String){Page(page:1,perPage:12){media(type:ANIME,search:$search,isAdult:false,sort:SEARCH_MATCH_DESC){id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status description genres episodes duration startDate{year} }}}`;const json=await request(ANILIST,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables:{search:q}})});if(json.errors?.length)throw new Error(json.errors[0].message||'AniList error');const data=(json.data?.Page?.media||[]).map(normalizeAniList);cache.set(key,{time:Date.now(),data});return data}}
async function searchAnime(q){const query=String(q||'').trim();return query?fetchJikan(`/anime?q=${encodeURIComponent(query)}&limit=12&sfw=true`):[]}
async function fetchCountdown(){const key='countdown';if(cache.has(key)&&Date.now()-cache.get(key).time<30000)return cache.get(key).data;const query=`query{Page(page:1,perPage:50){media(type:ANIME,status:RELEASING,isAdult:false,sort:START_DATE_DESC){id idMal title{romaji english native} coverImage{large extraLarge} averageScore format status episodes duration startDate{year} nextAiringEpisode{airingAt episode}}}}`;const json=await request(ANILIST,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});if(json.errors?.length)throw new Error(json.errors[0].message||'AniList error');const data=(json.data?.Page?.media||[]).map(normalizeAniList).filter(a=>a.nextEpisodeAt&&a.nextEpisodeAt>Date.now()).sort((a,b)=>a.nextEpisodeAt-b.nextEpisodeAt).slice(0,24);cache.set(key,{time:Date.now(),data});return data}
async function fetchAnimeDetails(id){const n=Number(id);if(!Number.isInteger(n)||n<1)throw new Error('Invalid anime id');const json=await request(`${JIKAN}/anime/${n}/full`);if(!json?.data)throw new Error('Anime not found');const a=normalizeJikan(json.data);a.trailer=json.data.trailer?.url||json.data.trailer?.embed_url||null;return a}
async function fetchAnimeRecommendations(id){const n=Number(id);if(!Number.isInteger(n)||n<1)throw new Error('Invalid anime id');const json=await request(`${JIKAN}/anime/${n}/recommendations`);return(Array.isArray(json.data)?json.data:[]).slice(0,12).map(x=>normalizeJikan(x.entry||{})).filter(x=>x.malId)}
function animeCard(a,extra=''){const title=a.englishTitle||a.title||'Unknown title';const img=a.image?`<img src="${escapeHtml(a.image)}" alt="${escapeHtml(title)}" loading="lazy" onerror="this.onerror=null;this.removeAttribute('src');this.alt='Anime poster unavailable';">`:'<div class="anime-card-image">🎌</div>';const detail=a.malId?`<a class="btn secondary" href="anime-detail.html?id=${encodeURIComponent(a.malId)}">Details</a>`:'';return`<article class="anime-card">${img}<div class="anime-card-copy"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(a.year||'—')} · ⭐ ${escapeHtml(a.score??'—')}</p><p>${escapeHtml(a.type||'Anime')} · ${escapeHtml(a.status||'Unknown')}</p><div class="card-actions">${detail}${extra}</div></div></article>`}
let firebasePromise;async function initFirebase(){if(firebasePromise)return firebasePromise;firebasePromise=(async()=>{const appM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`);const authM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`);const fsM=await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`);const app=appM.getApps().length?appM.getApps()[0]:appM.initializeApp(FIREBASE_CONFIG);const auth=authM.getAuth(app);const db=fsM.getFirestore(app);return{...authM,...fsM,auth,db}})();return firebasePromise}
async function getCurrentUser(){try{const f=await initFirebase();return f.auth.currentUser||await new Promise(resolve=>{let done=false;const stop=f.onAuthStateChanged(f.auth,u=>{if(done)return;done=true;stop();resolve(u||null)});setTimeout(()=>{if(!done){done=true;try{stop()}catch{}resolve(f.auth.currentUser||null)}},2500)})}catch{return null}}
function localSubs(){try{const x=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveLocal(x){localStorage.setItem(LOCAL_KEY,JSON.stringify(x))}
async function saveSubscription(item){const f=await initFirebase(),u=f.auth.currentUser;if(u){const id=String(item.id).replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,120);await f.setDoc(f.doc(f.db,'users',u.uid,'subscriptions',id),{...item,id,updated:new Date().toISOString()},{merge:true});return true}const list=localSubs(),i=list.findIndex(x=>String(x.id)===String(item.id));if(i>=0)list[i]=item;else list.push(item);saveLocal(list);return false}
async function deleteSubscription(id){const f=await initFirebase(),u=f.auth.currentUser;if(u){await f.deleteDoc(f.doc(f.db,'users',u.uid,'subscriptions',String(id).replace(/[^A-Za-z0-9:_-]/g,'_').slice(0,120)));return}saveLocal(localSubs().filter(x=>String(x.id)!==String(id)))}
async function loadSubscriptions(){const f=await initFirebase(),u=f.auth.currentUser;if(!u)return localSubs();const snap=await f.getDocs(f.collection(f.db,'users',u.uid,'subscriptions'));return snap.docs.map(d=>d.data())}
export{searchAnime,fetchJikan,fetchCountdown,fetchAnimeDetails,fetchAnimeRecommendations,animeCard,getAnimeId,escapeHtml,getCurrentUser,saveSubscription,deleteSubscription,loadSubscriptions};
